apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: goldenpath
  description: Catalog location for golden-path software templates
spec:
  targets:
    - ./templates/civicnet-node/template.yaml
    - ./templates/crypto-node/template.yaml
    - ./templates/golden-path/template.yaml
    - ./system-civicnet.yaml
    - ./domain-crypto.yaml
    - ./api-civicnet-node-rpc.yaml
    - ./resource-civicnet-node-data.yaml
    - ./users.yaml
    - ./group-guests.yaml
